#########################################
# Build Dependent Tasks                 #
#########################################
test:
  - 'jshint'
  - 'karma'

build:
  - 'sass'
  - 'handlebars'
  - 'requirejs'

release-beta:
  - 'copy'
  - 'aws_s3:staging'
  - 'invalidate_cloudfront:staging'

release-prod:
  - 'copy'
  - 'aws_s3:production'
  - 'invalidate_cloudfront:production'
#########################################
# END                                   #
#########################################


default:
  - 'concurrent:dev'

build-dev:
  - 'clean'
  - 'test'
  - 'build'
  - 'copy'

build-beta:
  - 'clean'
  - 'test'
  - 'build'
  - 'release-beta'

build-prod:
  - 'clean'
  - 'test'
  - 'build'
  - 'release-prod'
