default:
  - 'concurrent:dev'

test:
  - 'karma:thirdchannel'
  - 'karma:territory'

build-dev:
  - 'clean'
  - 'sass'
  - 'handlebars'
  - 'test'
  - 'requirejs'
  - 'copy'

build-beta:
  - 'clean'
  - 'sass'
  - 'handlebars'
  - 'test'
  - 'requirejs'
  - 'copy'
  - 'aws_s3:staging'
  - 'invalidate_cloudfront:staging'

build-prod:
  - 'clean'
  - 'sass'
  - 'handlebars'
  - 'test'
  - 'requirejs'
  - 'copy'
  - 'aws_s3:production'
  - 'invalidate_cloudfront:production'